### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by stdex** [Kurispy/neuralnet#1]
Hello.
What is format of input files? It's not byte array.

**Comment by Kurispy** [comment]
You're right, it's not. The input files are actually 120 \* 128 pixel intensity matrices. (They're just delimited really poorly.) If you have matlab, `reshape(m',[128,120])'` will reshape the matrices into the correct dimensions.

**Comment by stdex** [comment]
I do not quite understand how to get matrix like this from images in java...

**Comment by Kurispy** [comment]
I'd advise reading up on image processing in Java. There are probably plenty of good guides on that out on the internet.
